version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: login:v1.0
    restart: always
    container_name: api_login_v1
    networks:
      - red-gane-int
    # ports:
    #   - "4000:80"
networks:
  red-gane-int:
    external: true